[package]
authors = ["Kevin Cuzner <kevin@kevincuzner.com>"]
name = "stm32f031x"
version = "0.3.0"

[dependencies]
cortex-m = "0.5.0"
bare-metal = "0.2.0"
vcell = "0.1.0"

[dependencies.cortex-m-rt]
optional = true
version = "0.5.1"

[features]
rt = [ "cortex-m-rt/device" ]

