[tasks.build]
command = "xargo"
args = ["build"]
dependencies = ["clean"]

[tasks.build-release]
command = "xargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.svd2rust]
script = ["svd2rust -i STM32F031x.svd | rustfmt > src/stm32f031x.rs"]

[tasks.pre-build]
dependencies = [
]

[tasks.embedded-dump]
command = "./scripts/embedded.py"
args = ["--target=rt-soldering-iron", "dump"]

[tasks.embedded-copy-hex]
command = "./scripts/embedded.py"
args = ["--target=rt-soldering-iron", "copy", "ihex"]

[tasks.embedded-copy-bin]
command = "./scripts/embedded.py"
args = ["--target=rt-soldering-iron", "copy", "binary"]

[tasks.embedded-size]
command = "./scripts/embedded.py"
args = ["--target=rt-soldering-iron", "size"]

[tasks.embedded-dump-release]
command = "./scripts/embedded.py"
args = ["--release", "--target=rt-soldering-iron", "dump"]

[tasks.embedded-copy-hex-release]
command = "./scripts/embedded.py"
args = ["--release", "--target=rt-soldering-iron", "copy", "ihex"]

[tasks.embedded-copy-bin-release]
command = "./scripts/embedded.py"
args = ["--release", "--target=rt-soldering-iron", "copy", "binary"]

[tasks.embedded.size]
command = "./scripts/embedded.py"
args = ["--release", "--target=rt-soldering-iron", "size"]

[tasks.post-build]
dependencies = ["embedded-dump", "embedded-copy-hex", "embedded-size"]

[tasks.post-build-release]
dependencies = ["embedded-dump-release", "embedded-copy-hex-release", "embedded-size-release"]

[tasks.test-flow]
dependencies = []

[tasks.release-flow]
dependencies = [
    "format-flow",
    "pre-build",
    "build-release",
    "post-build-release",
    "test-flow"
]

